package theme

import (
	"crypto/sha256"
	"encoding/hex"
	"strconv"
	"strings"
)

// The generated stylesheet.
//
// # This function is the enforcement
//
// §4.12.2's claim is that "the protected variables above are never emitted into
// that stylesheet", and tokens.css hands the proof to this file: "the generator
// never emits a protected name — so a campaign cannot set one even by writing a
// raw .css into its content root". The property is structural rather than
// advisory, and it is structural because of what this file *cannot* do:
//
//   - it emits names by iterating `campaignVocabulary`, so the set of names it can
//     possibly write is the closed allowlist and nothing else;
//   - it emits values that have been through `parseColour`, so every value is
//     seven characters of `#` and lowercase hex;
//   - it writes no selector from input, no `url()`, no `@import`, and no media
//     query.
//
// Which means the sheet is not a template with holes in it. There is nowhere in
// it for a campaign's bytes to go, so there is no sanitising step that could be
// forgotten and no escaping question to get wrong. That is the whole design, and
// it is why `TestTheGeneratedStylesheetDeclaresNothingButTheBrandPair` can assert
// a shape rather than the absence of a pattern.
//
// # Why no `@media`, ever
//
// §10.7's rule is that no rule selecting TV mode may sit inside a `@media`
// naming `min-width`, `orientation`, `pointer` or `hover`, and §6.7's is that
// `prefers-*` and `forced-colors` are required in *every* mode. A generated sheet
// with no media query at all cannot violate either: it has no mode to select and
// no preference to honour. The brand pair is theme-independent by §4.12.4's own
// argument — one brand applies to both themes — so there is nothing here that
// *would* want a query.
//
// # Specificity, and why the selector is `:root[data-theme]`
//
// tokens.css declares `--brand-accent: var(--accent)` inside `[data-theme="light"]`
// and `[data-theme="dark"]`, both of which are specificity (0,1,0). A generated
// sheet declaring `:root` is *also* (0,1,0), so which wins comes down to which
// `<link>` comes last in the document — a coupling between this file and
// shell.templ that no test can see and that a reordering of the head would break
// silently.
//
// `:root[data-theme]` is (0,2,0) and outranks both without help. It also has a
// second property worth having: it matches **only** where the head resolver has
// written `data-theme`, so a document served to a visitor whose script did not run
// — or a reader whose browser dropped it — keeps the product's own brand, which is
// the fail-toward-default direction §4.12.3 asks for everywhere else.
// `TestTheGeneratedSelectorOutranksEveryThemeBlockInTheBuiltStylesheet` measures
// the claim against the built file rather than asserting the string.

// sheetSelector is what the generated declarations are scoped to.
//
// One selector, and the specificity argument above is why. Not `:root`, and not
// `html[data-theme]` — which would be equivalent in effect and one class *lower*,
// so a later revision choosing it would lose the property this selector exists for.
const sheetSelector = ":root[data-theme]"

// sheetHeader is the comment every generated sheet opens with.
//
// Fixed text. It names the file the sheet came from so that a reader inspecting
// `/c/{slug}/theme.css` in a network panel is looking at something they can
// change, and it carries no campaign value: a comment is a place to put a
// campaign's slug or its hex digits where a log line or a byte count could then
// expose them, and nothing here needs one.
const sheetHeader = `/* Generated by semiplane from the campaign's theme.yaml.
 * Do not edit this file: it is rewritten on every request. Edit theme.yaml
 * instead — semiplane validates it, and a token it will not accept is a token
 * this sheet will not carry. */`

// Manifest is a campaign's theme, validated and ready to serve.
//
// Opaque by construction: the only way to hold one is to have called `Parse` with
// bytes that passed, so a `Manifest` cannot be built around a colour that failed a
// floor. The generator takes a `brand` rather than a `Manifest` so that this type
// holds exactly the sheet and the one fact about it that the route needs.
type Manifest struct {
	// branded reports that this manifest named the brand pair. False for the
	// empty manifest and for a file that contained only comments.
	branded bool

	// sheet is the generated stylesheet, and it is never empty: a campaign with
	// no theme gets the header alone, which is a valid stylesheet and keeps the
	// route's response total.
	sheet string
}

// Sheet returns the generated stylesheet.
func (m Manifest) Sheet() string {
	return m.sheet
}

// Branded reports whether this manifest described a theme, as against being empty.
//
// The route uses it to decide between remembering a sheet and forgetting one, and
// the distinction is the difference between "this campaign has no theme" and "this
// campaign's theme was withdrawn" — the second of which must clear the first's
// remembered sheet, or a GM who deletes their manifest keeps their brand forever.
func (m Manifest) Branded() bool {
	return m.branded
}

// generate renders the stylesheet for a validated brand.
//
// Deterministic by construction: the declarations are emitted in the vocabulary's
// **sorted order**, taken from `campaignVocabulary` rather than from a hand-written
// pair here, so the same manifest always produces the same bytes and therefore the
// same `ETag`. A sheet whose bytes changed on a restart with no input change would
// revalidate as new on every deploy, which is the kind of defect that is invisible
// until somebody looks at a cache hit rate.
//
// Iterating the vocabulary rather than the validated map is also what makes the
// first claim in this file's header true without reading the rest of it: the set
// of names this function can write is the set of names a campaign may set, because
// it is the same set.
//
// The lookup is checked rather than assumed. A vocabulary that grows to a third
// name would otherwise make every campaign emit a declaration for the name its
// manifest did not set, and the zero colour — `#000000` — is a colour nobody
// chose: the pair rule catches this for the pair and nothing else catches it for
// whatever comes next.
func generate(branded brand) string {
	var sheet strings.Builder

	sheet.WriteString(sheetHeader)
	sheet.WriteString("\n")

	if !branded.branded {
		return sheet.String()
	}

	sheet.WriteString(sheetSelector)
	sheet.WriteString(" {\n")

	for _, name := range CampaignTokens() {
		value, named := branded.tokens[name]
		if !named {
			continue
		}

		writeDeclaration(&sheet, name, value)
	}

	sheet.WriteString("}\n")

	return sheet.String()
}

// writeDeclaration writes one custom property declaration, in the shape the
// browser reads and the shape the tests assert.
func writeDeclaration(sheet *strings.Builder, name string, value colour) {
	sheet.WriteString("  ")
	sheet.WriteString(name)
	sheet.WriteString(": ")
	sheet.WriteString(value.String())
	sheet.WriteString(";\n")
}

// sheetValidator is the `ETag` for one campaign's generated sheet.
//
// **Strong**, and unlike `assets.assetValidator`, which is weak because it hashes
// a hint rather than the bytes: this package has the whole representation in hand
// — it wrote it, in this function — so a strong validator costs nothing and is
// exactly true. Two consequences worth having: RFC 9110 §13.1.5 lets a client put
// this validator in an `If-Range`, and two responses claiming the same validator
// really are byte-identical.
//
// **Salted with the campaign id**, and that is S-8.3 made structural for the same
// reason `assets` salts: two campaigns whose manifests happen to agree describe
// the same brand for readers of different campaigns, and a validator that crossed
// between them would let one campaign's cache answer for the other's. The URL
// already differs, so this is belt to braces — but the brace is one line and the
// belt is a URL a proxy is entitled to rewrite.
//
// A separator joins the pre-image rather than concatenation, because `1` + `23`
// and `12` + `3` are the same string. That is the ambiguity `content.CacheKey`
// names and this is the same answer.
func sheetValidator(campaignID int64, sheet string) string {
	preimage := strconv.FormatInt(campaignID, 10) + validatorPreimageSep + sheet

	digest := sha256.Sum256([]byte(preimage))

	return `"` + hex.EncodeToString(digest[:]) + `"`
}

// validatorPreimageSep joins the validator's inputs. See sheetValidator.
const validatorPreimageSep = "\x00"
